# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres:14.1-alpine3.15
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: admin
      POSTGRES_DB: whyellow
    ports:
      - 5432:5432
    volumes:
      - C:\\Users\\martijn.dormans\\Documents\\_docker\\postgress:/var/lib/postgresql
